on: [push]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up our JDK environment
              uses: actions/setup-java@v1.4.3
              with:
                  java-version: 1.17
            - name: Build all artifacts
              id: buildAllApks
              uses: eskatos/gradle-command-action@v1.3.3
              with:
                  gradle-version: current
                  wrapper-cache-enabled: true
                  dependencies-cache-enabled: true
                  configuration-cache-enabled: true
                  arguments: build
